package siisoap.suministrofactemitidas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-25T13:04:45.210+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "siiService", 
                  wsdlLocation = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl",
                  targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl") 
public class SiiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", "siiService");
    public final static QName SuministroFactEmitidasPruebas = new QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", "SuministroFactEmitidasPruebas");
    static {
        URL url = null;
        try {
            url = new URL("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SiiService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SiiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SiiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SiiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SiiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SiiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SiiSOAP
     */
    @WebEndpoint(name = "SuministroFactEmitidasPruebas")
    public SiiSOAP getSuministroFactEmitidasPruebas() {
    	return super.getPort(SuministroFactEmitidasPruebas, SiiSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiiSOAP
     */
    @WebEndpoint(name = "SuministroFactEmitidasPruebas")
    public SiiSOAP getSuministroFactEmitidasPruebas(WebServiceFeature... features) {
        return super.getPort(SuministroFactEmitidasPruebas, SiiSOAP.class, features);
    }

}
