
package siisoap.suministrofactemitidas;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-25T13:04:45.116+02:00
 * Generated source version: 3.1.11
 * 
 */
public final class SiiSOAP_SuministroFactEmitidasPruebas_Client {

    private static final QName SERVICE_NAME = new QName("https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", "siiService");

    private SiiSOAP_SuministroFactEmitidasPruebas_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SiiService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SiiService ss = new SiiService(wsdlURL, SERVICE_NAME);
        SiiSOAP port = ss.getSuministroFactEmitidasPruebas();  
        
        {
        System.out.println("Invoking suministroLRFacturasEmitidas...");
        suministroinformacion.CabeceraSii _suministroLRFacturasEmitidas_cabeceraVal = new suministroinformacion.CabeceraSii();
        _suministroLRFacturasEmitidas_cabeceraVal.setIDVersionSii("IDVersionSii-1636032893");
        suministroinformacion.PersonaFisicaJuridicaESType _suministroLRFacturasEmitidas_cabeceraValTitular = new suministroinformacion.PersonaFisicaJuridicaESType();
        _suministroLRFacturasEmitidas_cabeceraValTitular.setNombreRazon("NombreRazon246677769");
        _suministroLRFacturasEmitidas_cabeceraValTitular.setNIFRepresentante("NIFRepresentante1287819136");
        _suministroLRFacturasEmitidas_cabeceraValTitular.setNIF("NIF-1662318572");
        _suministroLRFacturasEmitidas_cabeceraVal.setTitular(_suministroLRFacturasEmitidas_cabeceraValTitular);
        suministroinformacion.ClaveTipoComunicacionType _suministroLRFacturasEmitidas_cabeceraValTipoComunicacion = suministroinformacion.ClaveTipoComunicacionType.A_4;
        _suministroLRFacturasEmitidas_cabeceraVal.setTipoComunicacion(_suministroLRFacturasEmitidas_cabeceraValTipoComunicacion);
        javax.xml.ws.Holder<suministroinformacion.CabeceraSii> _suministroLRFacturasEmitidas_cabecera = new javax.xml.ws.Holder<suministroinformacion.CabeceraSii>(_suministroLRFacturasEmitidas_cabeceraVal);
        java.util.List<suministrolr.LRfacturasEmitidasType> _suministroLRFacturasEmitidas_registroLRFacturasEmitidas = new java.util.ArrayList<suministrolr.LRfacturasEmitidasType>();
        suministrolr.LRfacturasEmitidasType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1 = new suministrolr.LRfacturasEmitidasType();
        suministroinformacion.RegistroSii.PeriodoImpositivo _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1PeriodoImpositivo = new suministroinformacion.RegistroSii.PeriodoImpositivo();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1PeriodoImpositivo.setEjercicio("Ejercicio933426353");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1PeriodoImpositivo.setPeriodo("Periodo1261203134");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1.setPeriodoImpositivo(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1PeriodoImpositivo);
        suministroinformacion.IDFacturaExpedidaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFactura = new suministroinformacion.IDFacturaExpedidaType();
        suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFacturaIDEmisorFactura = new suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFacturaIDEmisorFactura.setNIF("NIF-1285134546");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFactura.setIDEmisorFactura(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFacturaIDEmisorFactura);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFactura.setNumSerieFacturaEmisor("NumSerieFacturaEmisor1668226440");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFactura.setNumSerieFacturaEmisorResumenFin("NumSerieFacturaEmisorResumenFin1833455743");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFactura.setFechaExpedicionFacturaEmisor("FechaExpedicionFacturaEmisor-1867090200");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1.setIDFactura(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1IDFactura);
        suministroinformacion.FacturaExpedidaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida = new suministroinformacion.FacturaExpedidaType();
        suministroinformacion.ClaveTipoFacturaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoFactura = suministroinformacion.ClaveTipoFacturaType.R_4;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setTipoFactura(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoFactura);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setTipoRectificativa("TipoRectificativa400051732");
        suministroinformacion.FacturaType.FacturasAgrupadas _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasAgrupadas = new suministroinformacion.FacturaType.FacturasAgrupadas();
        java.util.List<suministroinformacion.IDFacturaARType> _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasAgrupadasIDFacturaAgrupada = new java.util.ArrayList<suministroinformacion.IDFacturaARType>();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasAgrupadas.getIDFacturaAgrupada().addAll(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasAgrupadasIDFacturaAgrupada);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setFacturasAgrupadas(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasAgrupadas);
        suministroinformacion.FacturaType.FacturasRectificadas _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasRectificadas = new suministroinformacion.FacturaType.FacturasRectificadas();
        java.util.List<suministroinformacion.IDFacturaARType> _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasRectificadasIDFacturaRectificada = new java.util.ArrayList<suministroinformacion.IDFacturaARType>();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasRectificadas.getIDFacturaRectificada().addAll(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasRectificadasIDFacturaRectificada);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setFacturasRectificadas(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaFacturasRectificadas);
        suministroinformacion.DesgloseRectificacionType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaImporteRectificacion = new suministroinformacion.DesgloseRectificacionType();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaImporteRectificacion.setBaseRectificada("BaseRectificada1838010600");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaImporteRectificacion.setCuotaRectificada("CuotaRectificada-1913140999");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaImporteRectificacion.setCuotaRecargoRectificado("CuotaRecargoRectificado778194435");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setImporteRectificacion(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaImporteRectificacion);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setFechaOperacion("FechaOperacion47166533");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setClaveRegimenEspecialOTrascendencia("ClaveRegimenEspecialOTrascendencia-92874394");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setClaveRegimenEspecialOTrascendenciaAdicional1("ClaveRegimenEspecialOTrascendenciaAdicional145295493");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setClaveRegimenEspecialOTrascendenciaAdicional2("ClaveRegimenEspecialOTrascendenciaAdicional2369312049");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setNumRegistroAcuerdoFacturacion("NumRegistroAcuerdoFacturacion1909870809");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setImporteTotal("ImporteTotal1958057391");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setBaseImponibleACoste("BaseImponibleACoste2132464086");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setDescripcionOperacion("DescripcionOperacion1628315211");
        suministroinformacion.FacturaExpedidaType.DatosInmueble _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaDatosInmueble = new suministroinformacion.FacturaExpedidaType.DatosInmueble();
        java.util.List<suministroinformacion.DatosInmuebleType> _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaDatosInmuebleDetalleInmueble = new java.util.ArrayList<suministroinformacion.DatosInmuebleType>();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaDatosInmueble.getDetalleInmueble().addAll(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaDatosInmuebleDetalleInmueble);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setDatosInmueble(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaDatosInmueble);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setImporteTransmisionSujetoAIVA("ImporteTransmisionSujetoAIVA1172214645");
        suministroinformacion.EmitidaPorTercerosType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaEmitidaPorTerceros = suministroinformacion.EmitidaPorTercerosType.S;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setEmitidaPorTerceros(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaEmitidaPorTerceros);
        suministroinformacion.VariosDestinatariosType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaVariosDestinatarios = suministroinformacion.VariosDestinatariosType.N;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setVariosDestinatarios(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaVariosDestinatarios);
        suministroinformacion.CuponType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaCupon = suministroinformacion.CuponType.N;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setCupon(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaCupon);
        suministroinformacion.PersonaFisicaJuridicaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparte = new suministroinformacion.PersonaFisicaJuridicaType();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparte.setNombreRazon("NombreRazon730135713");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparte.setNIFRepresentante("NIFRepresentante-544024674");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparte.setNIF("NIF-1962434251");
        suministroinformacion.IDOtroType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparteIDOtro = new suministroinformacion.IDOtroType();
        suministroinformacion.CountryType2 _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparteIDOtroCodigoPais = suministroinformacion.CountryType2.IO;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparteIDOtro.setCodigoPais(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparteIDOtroCodigoPais);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparteIDOtro.setIDType("IDType262298647");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparteIDOtro.setID("ID1825207852");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparte.setIDOtro(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparteIDOtro);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setContraparte(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaContraparte);
        suministroinformacion.FacturaExpedidaType.TipoDesglose _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesglose = new suministroinformacion.FacturaExpedidaType.TipoDesglose();
        suministroinformacion.TipoSinDesgloseType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFactura = new suministroinformacion.TipoSinDesgloseType();
        suministroinformacion.SujetaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujeta = new suministroinformacion.SujetaType();
        suministroinformacion.SujetaType.Exenta _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaExenta = new suministroinformacion.SujetaType.Exenta();
        suministroinformacion.CausaExencionType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaExentaCausaExencion = suministroinformacion.CausaExencionType.E_4;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaExenta.setCausaExencion(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaExentaCausaExencion);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaExenta.setBaseImponible("BaseImponible-497309007");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujeta.setExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaExenta);
        suministroinformacion.SujetaType.NoExenta _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExenta = new suministroinformacion.SujetaType.NoExenta();
        suministroinformacion.TipoOperacionSujetaNoExentaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExentaTipoNoExenta = suministroinformacion.TipoOperacionSujetaNoExentaType.S_2;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExenta.setTipoNoExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExentaTipoNoExenta);
        suministroinformacion.SujetaType.NoExenta.DesgloseIVA _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVA = new suministroinformacion.SujetaType.NoExenta.DesgloseIVA();
        java.util.List<suministroinformacion.DetalleIVAEmitidaType> _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVADetalleIVA = new java.util.ArrayList<suministroinformacion.DetalleIVAEmitidaType>();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVA.getDetalleIVA().addAll(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVADetalleIVA);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExenta.setDesgloseIVA(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVA);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujeta.setNoExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujetaNoExenta);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFactura.setSujeta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaSujeta);
        suministroinformacion.NoSujetaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaNoSujeta = new suministroinformacion.NoSujetaType();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaNoSujeta.setImportePorArticulos714Otros("ImportePorArticulos714Otros2065656703");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaNoSujeta.setImporteTAIReglasLocalizacion("ImporteTAIReglasLocalizacion1859607837");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFactura.setNoSujeta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFacturaNoSujeta);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesglose.setDesgloseFactura(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseFactura);
        suministroinformacion.TipoConDesgloseType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacion = new suministroinformacion.TipoConDesgloseType();
        suministroinformacion.TipoSinDesglosePrestacionType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios = new suministroinformacion.TipoSinDesglosePrestacionType();
        suministroinformacion.SujetaPrestacionType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta = new suministroinformacion.SujetaPrestacionType();
        suministroinformacion.SujetaPrestacionType.Exenta _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta = new suministroinformacion.SujetaPrestacionType.Exenta();
        suministroinformacion.CausaExencionType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExentaCausaExencion = suministroinformacion.CausaExencionType.E_3;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta.setCausaExencion(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExentaCausaExencion);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta.setBaseImponible("BaseImponible2075386862");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta.setExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta);
        suministroinformacion.SujetaPrestacionType.NoExenta _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta = new suministroinformacion.SujetaPrestacionType.NoExenta();
        suministroinformacion.TipoOperacionSujetaNoExentaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaTipoNoExenta = suministroinformacion.TipoOperacionSujetaNoExentaType.S_1;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta.setTipoNoExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaTipoNoExenta);
        suministroinformacion.SujetaPrestacionType.NoExenta.DesgloseIVA _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVA = new suministroinformacion.SujetaPrestacionType.NoExenta.DesgloseIVA();
        java.util.List<suministroinformacion.DetalleIVAEmitidaPrestacionType> _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVADetalleIVA = new java.util.ArrayList<suministroinformacion.DetalleIVAEmitidaPrestacionType>();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVA.getDetalleIVA().addAll(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVADetalleIVA);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta.setDesgloseIVA(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVA);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta.setNoExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios.setSujeta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta);
        suministroinformacion.NoSujetaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta = new suministroinformacion.NoSujetaType();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta.setImportePorArticulos714Otros("ImportePorArticulos714Otros-71039856");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta.setImporteTAIReglasLocalizacion("ImporteTAIReglasLocalizacion-843989929");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios.setNoSujeta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacion.setPrestacionServicios(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios);
        suministroinformacion.TipoSinDesgloseType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntrega = new suministroinformacion.TipoSinDesgloseType();
        suministroinformacion.SujetaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta = new suministroinformacion.SujetaType();
        suministroinformacion.SujetaType.Exenta _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta = new suministroinformacion.SujetaType.Exenta();
        suministroinformacion.CausaExencionType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExentaCausaExencion = suministroinformacion.CausaExencionType.E_3;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta.setCausaExencion(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExentaCausaExencion);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta.setBaseImponible("BaseImponible2036512976");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta.setExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta);
        suministroinformacion.SujetaType.NoExenta _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta = new suministroinformacion.SujetaType.NoExenta();
        suministroinformacion.TipoOperacionSujetaNoExentaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaTipoNoExenta = suministroinformacion.TipoOperacionSujetaNoExentaType.S_3;
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta.setTipoNoExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaTipoNoExenta);
        suministroinformacion.SujetaType.NoExenta.DesgloseIVA _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVA = new suministroinformacion.SujetaType.NoExenta.DesgloseIVA();
        java.util.List<suministroinformacion.DetalleIVAEmitidaType> _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVADetalleIVA = new java.util.ArrayList<suministroinformacion.DetalleIVAEmitidaType>();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVA.getDetalleIVA().addAll(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVADetalleIVA);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta.setDesgloseIVA(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVA);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta.setNoExenta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntrega.setSujeta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta);
        suministroinformacion.NoSujetaType _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta = new suministroinformacion.NoSujetaType();
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta.setImportePorArticulos714Otros("ImportePorArticulos714Otros-1215891135");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta.setImporteTAIReglasLocalizacion("ImporteTAIReglasLocalizacion463374850");
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntrega.setNoSujeta(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacion.setEntrega(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacionEntrega);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesglose.setDesgloseTipoOperacion(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesgloseDesgloseTipoOperacion);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida.setTipoDesglose(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedidaTipoDesglose);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1.setFacturaExpedida(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1FacturaExpedida);
        _suministroLRFacturasEmitidas_registroLRFacturasEmitidas.add(_suministroLRFacturasEmitidas_registroLRFacturasEmitidasVal1);
        javax.xml.ws.Holder<java.lang.String> _suministroLRFacturasEmitidas_csv = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<suministroinformacion.DatosPresentacionType> _suministroLRFacturasEmitidas_datosPresentacion = new javax.xml.ws.Holder<suministroinformacion.DatosPresentacionType>();
        javax.xml.ws.Holder<respuestasuministro.EstadoEnvioType> _suministroLRFacturasEmitidas_estadoEnvio = new javax.xml.ws.Holder<respuestasuministro.EstadoEnvioType>();
        javax.xml.ws.Holder<java.util.List<respuestasuministro.RespuestaExpedidaType>> _suministroLRFacturasEmitidas_respuestaLinea = new javax.xml.ws.Holder<java.util.List<respuestasuministro.RespuestaExpedidaType>>();
        port.suministroLRFacturasEmitidas(_suministroLRFacturasEmitidas_cabecera, _suministroLRFacturasEmitidas_registroLRFacturasEmitidas, _suministroLRFacturasEmitidas_csv, _suministroLRFacturasEmitidas_datosPresentacion, _suministroLRFacturasEmitidas_estadoEnvio, _suministroLRFacturasEmitidas_respuestaLinea);

        System.out.println("suministroLRFacturasEmitidas._suministroLRFacturasEmitidas_cabecera=" + _suministroLRFacturasEmitidas_cabecera.value);
        System.out.println("suministroLRFacturasEmitidas._suministroLRFacturasEmitidas_csv=" + _suministroLRFacturasEmitidas_csv.value);
        System.out.println("suministroLRFacturasEmitidas._suministroLRFacturasEmitidas_datosPresentacion=" + _suministroLRFacturasEmitidas_datosPresentacion.value);
        System.out.println("suministroLRFacturasEmitidas._suministroLRFacturasEmitidas_estadoEnvio=" + _suministroLRFacturasEmitidas_estadoEnvio.value);
        System.out.println("suministroLRFacturasEmitidas._suministroLRFacturasEmitidas_respuestaLinea=" + _suministroLRFacturasEmitidas_respuestaLinea.value);

        }
        {
        System.out.println("Invoking consultaLRFacturasEmitidas...");
        suministroinformacion.CabeceraConsultaSii _consultaLRFacturasEmitidas_cabecera = new suministroinformacion.CabeceraConsultaSii();
        _consultaLRFacturasEmitidas_cabecera.setIDVersionSii("IDVersionSii919491889");
        suministroinformacion.PersonaFisicaJuridicaUnicaESType _consultaLRFacturasEmitidas_cabeceraTitular = new suministroinformacion.PersonaFisicaJuridicaUnicaESType();
        _consultaLRFacturasEmitidas_cabeceraTitular.setNombreRazon("NombreRazon1297343339");
        _consultaLRFacturasEmitidas_cabeceraTitular.setNIF("NIF-156683535");
        _consultaLRFacturasEmitidas_cabecera.setTitular(_consultaLRFacturasEmitidas_cabeceraTitular);
        consultalr.LRFiltroEmitidasType _consultaLRFacturasEmitidas_filtroConsulta = new consultalr.LRFiltroEmitidasType();
        suministroinformacion.RegistroSii.PeriodoImpositivo _consultaLRFacturasEmitidas_filtroConsultaPeriodoImpositivo = new suministroinformacion.RegistroSii.PeriodoImpositivo();
        _consultaLRFacturasEmitidas_filtroConsultaPeriodoImpositivo.setEjercicio("Ejercicio628223429");
        _consultaLRFacturasEmitidas_filtroConsultaPeriodoImpositivo.setPeriodo("Periodo-2126128060");
        _consultaLRFacturasEmitidas_filtroConsulta.setPeriodoImpositivo(_consultaLRFacturasEmitidas_filtroConsultaPeriodoImpositivo);
        suministroinformacion.IDFacturaConsulta2Type _consultaLRFacturasEmitidas_filtroConsultaIDFactura = new suministroinformacion.IDFacturaConsulta2Type();
        _consultaLRFacturasEmitidas_filtroConsultaIDFactura.setNumSerieFacturaEmisor("NumSerieFacturaEmisor-1653617579");
        _consultaLRFacturasEmitidas_filtroConsultaIDFactura.setFechaExpedicionFacturaEmisor("FechaExpedicionFacturaEmisor-132981402");
        _consultaLRFacturasEmitidas_filtroConsulta.setIDFactura(_consultaLRFacturasEmitidas_filtroConsultaIDFactura);
        suministroinformacion.ContraparteConsultaType _consultaLRFacturasEmitidas_filtroConsultaContraparte = new suministroinformacion.ContraparteConsultaType();
        _consultaLRFacturasEmitidas_filtroConsultaContraparte.setNombreRazon("NombreRazon1799789341");
        _consultaLRFacturasEmitidas_filtroConsultaContraparte.setNIF("NIF-233159111");
        suministroinformacion.IDOtroType _consultaLRFacturasEmitidas_filtroConsultaContraparteIDOtro = new suministroinformacion.IDOtroType();
        suministroinformacion.CountryType2 _consultaLRFacturasEmitidas_filtroConsultaContraparteIDOtroCodigoPais = suministroinformacion.CountryType2.AS;
        _consultaLRFacturasEmitidas_filtroConsultaContraparteIDOtro.setCodigoPais(_consultaLRFacturasEmitidas_filtroConsultaContraparteIDOtroCodigoPais);
        _consultaLRFacturasEmitidas_filtroConsultaContraparteIDOtro.setIDType("IDType-1224270178");
        _consultaLRFacturasEmitidas_filtroConsultaContraparteIDOtro.setID("ID-337713048");
        _consultaLRFacturasEmitidas_filtroConsultaContraparte.setIDOtro(_consultaLRFacturasEmitidas_filtroConsultaContraparteIDOtro);
        _consultaLRFacturasEmitidas_filtroConsulta.setContraparte(_consultaLRFacturasEmitidas_filtroConsultaContraparte);
        suministroinformacion.RangoFechaPresentacionType _consultaLRFacturasEmitidas_filtroConsultaFechaPresentacion = new suministroinformacion.RangoFechaPresentacionType();
        _consultaLRFacturasEmitidas_filtroConsultaFechaPresentacion.setDesde("Desde-153511358");
        _consultaLRFacturasEmitidas_filtroConsultaFechaPresentacion.setHasta("Hasta-1113520410");
        _consultaLRFacturasEmitidas_filtroConsulta.setFechaPresentacion(_consultaLRFacturasEmitidas_filtroConsultaFechaPresentacion);
        suministroinformacion.FacturaModificadaType _consultaLRFacturasEmitidas_filtroConsultaFacturaModificada = suministroinformacion.FacturaModificadaType.N;
        _consultaLRFacturasEmitidas_filtroConsulta.setFacturaModificada(_consultaLRFacturasEmitidas_filtroConsultaFacturaModificada);
        _consultaLRFacturasEmitidas_filtroConsulta.setEstadoCuadre("EstadoCuadre1896334927");
        suministroinformacion.IDFacturaExpedidaBCType _consultaLRFacturasEmitidas_filtroConsultaClavePaginacion = new suministroinformacion.IDFacturaExpedidaBCType();
        suministroinformacion.IDFacturaExpedidaBCType.IDEmisorFactura _consultaLRFacturasEmitidas_filtroConsultaClavePaginacionIDEmisorFactura = new suministroinformacion.IDFacturaExpedidaBCType.IDEmisorFactura();
        _consultaLRFacturasEmitidas_filtroConsultaClavePaginacionIDEmisorFactura.setNIF("NIF-1795091574");
        _consultaLRFacturasEmitidas_filtroConsultaClavePaginacion.setIDEmisorFactura(_consultaLRFacturasEmitidas_filtroConsultaClavePaginacionIDEmisorFactura);
        _consultaLRFacturasEmitidas_filtroConsultaClavePaginacion.setNumSerieFacturaEmisor("NumSerieFacturaEmisor1983625455");
        _consultaLRFacturasEmitidas_filtroConsultaClavePaginacion.setFechaExpedicionFacturaEmisor("FechaExpedicionFacturaEmisor-1059251826");
        _consultaLRFacturasEmitidas_filtroConsulta.setClavePaginacion(_consultaLRFacturasEmitidas_filtroConsultaClavePaginacion);
        java.util.List<respuestaconsultalr.RegistroRespuestaConsultaEmitidasType> _consultaLRFacturasEmitidas__return = port.consultaLRFacturasEmitidas(_consultaLRFacturasEmitidas_cabecera, _consultaLRFacturasEmitidas_filtroConsulta);
        System.out.println("consultaLRFacturasEmitidas.result=" + _consultaLRFacturasEmitidas__return);


        }
        {
        System.out.println("Invoking anulacionLRFacturasEmitidas...");
        suministrolr.BajaLRFacturasEmitidas _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidas = new suministrolr.BajaLRFacturasEmitidas();
        suministroinformacion.CabeceraSiiBaja _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabecera = new suministroinformacion.CabeceraSiiBaja();
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabecera.setIDVersionSii("IDVersionSii-429936565");
        suministroinformacion.PersonaFisicaJuridicaESType _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabeceraTitular = new suministroinformacion.PersonaFisicaJuridicaESType();
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabeceraTitular.setNombreRazon("NombreRazon1249386852");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabeceraTitular.setNIFRepresentante("NIFRepresentante-531870337");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabeceraTitular.setNIF("NIF914405630");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabecera.setTitular(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabeceraTitular);
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidas.setCabecera(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasCabecera);
        java.util.List<suministrolr.LRBajaExpedidasType> _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidas = new java.util.ArrayList<suministrolr.LRBajaExpedidasType>();
        suministrolr.LRBajaExpedidasType _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1 = new suministrolr.LRBajaExpedidasType();
        suministroinformacion.RegistroSii.PeriodoImpositivo _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1PeriodoImpositivo = new suministroinformacion.RegistroSii.PeriodoImpositivo();
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1PeriodoImpositivo.setEjercicio("Ejercicio-1568824981");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1PeriodoImpositivo.setPeriodo("Periodo-809584953");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1.setPeriodoImpositivo(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1PeriodoImpositivo);
        suministroinformacion.IDFacturaExpedidaBCType _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFactura = new suministroinformacion.IDFacturaExpedidaBCType();
        suministroinformacion.IDFacturaExpedidaBCType.IDEmisorFactura _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFacturaIDEmisorFactura = new suministroinformacion.IDFacturaExpedidaBCType.IDEmisorFactura();
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFacturaIDEmisorFactura.setNIF("NIF-1199061276");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFactura.setIDEmisorFactura(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFacturaIDEmisorFactura);
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFactura.setNumSerieFacturaEmisor("NumSerieFacturaEmisor314635912");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFactura.setFechaExpedicionFacturaEmisor("FechaExpedicionFacturaEmisor-452193965");
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1.setIDFactura(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1IDFactura);
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidas.add(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidasVal1);
        _anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidas.getRegistroLRBajaExpedidas().addAll(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidasRegistroLRBajaExpedidas);
        respuestasuministro.RespuestaLRBajaFEmitidasType _anulacionLRFacturasEmitidas__return = port.anulacionLRFacturasEmitidas(_anulacionLRFacturasEmitidas_anulacionLRFacturasEmitidas);
        System.out.println("anulacionLRFacturasEmitidas.result=" + _anulacionLRFacturasEmitidas__return);


        }

        System.exit(0);
    }

}
