package siisoap.suministrofactemitidas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-25T13:04:45.194+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl", name = "siiSOAP")
@XmlSeeAlso({respuestasuministro.ObjectFactory.class, suministroinformacion.ObjectFactory.class, respuestaconsultalr.ObjectFactory.class, consultalr.ObjectFactory.class, suministrolr.ObjectFactory.class})
public interface SiiSOAP {

    @WebMethod(operationName = "SuministroLRFacturasEmitidas")
    //@RequestWrapper(localName = "SuministroLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroLR.xsd", className = "https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.suministrolr.SuministroLRFacturasEmitidas")
    @RequestWrapper(localName = "SuministroLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroLR.xsd", className = "suministrolr.SuministroLRFacturasEmitidas")
    //@ResponseWrapper(localName = "RespuestaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd", className = "https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.respuestasuministro.RespuestaLRFEmitidasType")
    @ResponseWrapper(localName = "RespuestaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd", className = "respuestasuministro.RespuestaLRFEmitidasType")
    public void suministroLRFacturasEmitidas(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Cabecera", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd")
        javax.xml.ws.Holder<suministroinformacion.CabeceraSii> cabecera,
        @WebParam(name = "RegistroLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroLR.xsd")
        java.util.List<suministrolr.LRfacturasEmitidasType> registroLRFacturasEmitidas,
        @WebParam(mode = WebParam.Mode.OUT, name = "CSV", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd")
        javax.xml.ws.Holder<java.lang.String> csv,
        @WebParam(mode = WebParam.Mode.OUT, name = "DatosPresentacion", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd")
        javax.xml.ws.Holder<suministroinformacion.DatosPresentacionType> datosPresentacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "EstadoEnvio", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd")
        javax.xml.ws.Holder<respuestasuministro.EstadoEnvioType> estadoEnvio,
        @WebParam(mode = WebParam.Mode.OUT, name = "RespuestaLinea", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd")
        javax.xml.ws.Holder<java.util.List<respuestasuministro.RespuestaExpedidaType>> respuestaLinea
    );

    @WebMethod(operationName = "ConsultaLRFacturasEmitidas")
//    @RequestWrapper(localName = "ConsultaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/ConsultaLR.xsd", className = "https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.consultalr.LRConsultaEmitidasType")
//    @ResponseWrapper(localName = "RespuestaConsultaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaConsultaLR.xsd", className = "https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.respuestaconsultalr.RespuestaConsultaLRFacturasEmitidasType")
    @RequestWrapper(localName = "ConsultaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/ConsultaLR.xsd", className = "consultalr.LRConsultaEmitidasType")
    @ResponseWrapper(localName = "RespuestaConsultaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaConsultaLR.xsd", className = "respuestaconsultalr.RespuestaConsultaLRFacturasEmitidasType")
    @WebResult(name = "RegistroRespuestaConsultaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaConsultaLR.xsd")
    public java.util.List<respuestaconsultalr.RegistroRespuestaConsultaEmitidasType> consultaLRFacturasEmitidas(
        @WebParam(name = "Cabecera", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroInformacion.xsd")
        suministroinformacion.CabeceraConsultaSii cabecera,
        @WebParam(name = "FiltroConsulta", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/ConsultaLR.xsd")
        consultalr.LRFiltroEmitidasType filtroConsulta
    );

    @WebMethod(operationName = "AnulacionLRFacturasEmitidas")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "RespuestaLRBajaFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/RespuestaSuministro.xsd", partName = "RespuestaLAnulacionRFacturasEmitidas")
    public respuestasuministro.RespuestaLRBajaFEmitidasType anulacionLRFacturasEmitidas(
        @WebParam(partName = "AnulacionLRFacturasEmitidas", name = "BajaLRFacturasEmitidas", targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroLR.xsd")
        suministrolr.BajaLRFacturasEmitidas anulacionLRFacturasEmitidas
    );
}
