
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package siisoap.suministrofactemitidas;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-25T13:04:45.179+02:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "siiService",
                      portName = "SuministroFactEmitidasPruebas",
                      targetNamespace = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl",
                      wsdlLocation = "https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroFactEmitidas.wsdl",
                      endpointInterface = "siisoap.suministrofactemitidas.SiiSOAP")
                      
public class SuministroFactEmitidasPruebasImpl implements SiiSOAP {

    private static final Logger LOG = Logger.getLogger(SuministroFactEmitidasPruebasImpl.class.getName());

    /* (non-Javadoc)
     * @see siisoap.suministrofactemitidas.SiiSOAP#suministroLRFacturasEmitidas(https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.suministroinformacion.CabeceraSii cabecera, java.util.List<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.suministrolr.LRfacturasEmitidasType> registroLRFacturasEmitidas, java.lang.String csv, https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.suministroinformacion.DatosPresentacionType datosPresentacion, https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.respuestasuministro.EstadoEnvioType estadoEnvio, java.util.List<https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.respuestasuministro.RespuestaExpedidaType> respuestaLinea)*
     */
    public void suministroLRFacturasEmitidas(javax.xml.ws.Holder<suministroinformacion.CabeceraSii> cabecera, java.util.List<suministrolr.LRfacturasEmitidasType> registroLRFacturasEmitidas, javax.xml.ws.Holder<java.lang.String> csv, javax.xml.ws.Holder<suministroinformacion.DatosPresentacionType> datosPresentacion, javax.xml.ws.Holder<respuestasuministro.EstadoEnvioType> estadoEnvio, javax.xml.ws.Holder<java.util.List<respuestasuministro.RespuestaExpedidaType>> respuestaLinea) { 
        LOG.info("Executing operation suministroLRFacturasEmitidas");
        System.out.println(cabecera.value);
        System.out.println(registroLRFacturasEmitidas);
        try {
            java.lang.String csvValue = "csvValue-1066623750";
            csv.value = csvValue;
            suministroinformacion.DatosPresentacionType datosPresentacionValue = new suministroinformacion.DatosPresentacionType();
            datosPresentacionValue.setNIFPresentador("NIFPresentador-577293219");
            datosPresentacionValue.setTimestampPresentacion("TimestampPresentacion2049944988");
            datosPresentacion.value = datosPresentacionValue;
            respuestasuministro.EstadoEnvioType estadoEnvioValue = respuestasuministro.EstadoEnvioType.INCORRECTO;
            estadoEnvio.value = estadoEnvioValue;
            java.util.List<respuestasuministro.RespuestaExpedidaType> respuestaLineaValue = new java.util.ArrayList<respuestasuministro.RespuestaExpedidaType>();
            respuestasuministro.RespuestaExpedidaType respuestaLineaValueVal1 = new respuestasuministro.RespuestaExpedidaType();
            suministroinformacion.IDFacturaExpedidaType respuestaLineaValueVal1IDFactura = new suministroinformacion.IDFacturaExpedidaType();
            suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura respuestaLineaValueVal1IDFacturaIDEmisorFactura = new suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura();
            respuestaLineaValueVal1IDFacturaIDEmisorFactura.setNIF("NIF-297353845");
            respuestaLineaValueVal1IDFactura.setIDEmisorFactura(respuestaLineaValueVal1IDFacturaIDEmisorFactura);
            respuestaLineaValueVal1IDFactura.setNumSerieFacturaEmisor("NumSerieFacturaEmisor-1786157312");
            respuestaLineaValueVal1IDFactura.setNumSerieFacturaEmisorResumenFin("NumSerieFacturaEmisorResumenFin-1059340443");
            respuestaLineaValueVal1IDFactura.setFechaExpedicionFacturaEmisor("FechaExpedicionFacturaEmisor1234584297");
            respuestaLineaValueVal1.setIDFactura(respuestaLineaValueVal1IDFactura);
            respuestasuministro.EstadoRegistroType respuestaLineaValueVal1EstadoRegistro = respuestasuministro.EstadoRegistroType.CORRECTO;
            respuestaLineaValueVal1.setEstadoRegistro(respuestaLineaValueVal1EstadoRegistro);
            respuestaLineaValueVal1.setCodigoErrorRegistro(new java.math.BigInteger("80480918113600258816458501063872916511"));
            respuestaLineaValueVal1.setDescripcionErrorRegistro("DescripcionErrorRegistro-1734856094");
            respuestaLineaValueVal1.setCSV("CSV2020213650");
            respuestaLineaValue.add(respuestaLineaValueVal1);
            respuestaLinea.value = respuestaLineaValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see siisoap.suministrofactemitidas.SiiSOAP#consultaLRFacturasEmitidas(https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.suministroinformacion.CabeceraConsultaSii cabecera, https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.consultalr.LRFiltroEmitidasType filtroConsulta)*
     */
    public java.util.List<respuestaconsultalr.RegistroRespuestaConsultaEmitidasType> consultaLRFacturasEmitidas(suministroinformacion.CabeceraConsultaSii cabecera, consultalr.LRFiltroEmitidasType filtroConsulta) { 
        LOG.info("Executing operation consultaLRFacturasEmitidas");
        System.out.println(cabecera);
        System.out.println(filtroConsulta);
        try {
            java.util.List<respuestaconsultalr.RegistroRespuestaConsultaEmitidasType> _return = new java.util.ArrayList<respuestaconsultalr.RegistroRespuestaConsultaEmitidasType>();
            respuestaconsultalr.RegistroRespuestaConsultaEmitidasType _returnVal1 = new respuestaconsultalr.RegistroRespuestaConsultaEmitidasType();
            suministroinformacion.IDFacturaExpedidaType _returnVal1IDFactura = new suministroinformacion.IDFacturaExpedidaType();
            suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura _returnVal1IDFacturaIDEmisorFactura = new suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura();
            _returnVal1IDFacturaIDEmisorFactura.setNIF("NIF-1452059526");
            _returnVal1IDFactura.setIDEmisorFactura(_returnVal1IDFacturaIDEmisorFactura);
            _returnVal1IDFactura.setNumSerieFacturaEmisor("NumSerieFacturaEmisor475999548");
            _returnVal1IDFactura.setNumSerieFacturaEmisorResumenFin("NumSerieFacturaEmisorResumenFin-106825216");
            _returnVal1IDFactura.setFechaExpedicionFacturaEmisor("FechaExpedicionFacturaEmisor502328350");
            _returnVal1.setIDFactura(_returnVal1IDFactura);
            respuestaconsultalr.FacturaRespuestaExpedidaType _returnVal1DatosFacturaEmitida = new respuestaconsultalr.FacturaRespuestaExpedidaType();
            suministroinformacion.ClaveTipoFacturaType _returnVal1DatosFacturaEmitidaTipoFactura = suministroinformacion.ClaveTipoFacturaType.F_1;
            _returnVal1DatosFacturaEmitida.setTipoFactura(_returnVal1DatosFacturaEmitidaTipoFactura);
            _returnVal1DatosFacturaEmitida.setTipoRectificativa("TipoRectificativa-1591533878");
            respuestaconsultalr.FacturaRespuestaType.FacturasAgrupadas _returnVal1DatosFacturaEmitidaFacturasAgrupadas = new respuestaconsultalr.FacturaRespuestaType.FacturasAgrupadas();
            java.util.List<suministroinformacion.IDFacturaARType> _returnVal1DatosFacturaEmitidaFacturasAgrupadasIDFacturaAgrupada = new java.util.ArrayList<suministroinformacion.IDFacturaARType>();
            _returnVal1DatosFacturaEmitidaFacturasAgrupadas.getIDFacturaAgrupada().addAll(_returnVal1DatosFacturaEmitidaFacturasAgrupadasIDFacturaAgrupada);
            _returnVal1DatosFacturaEmitida.setFacturasAgrupadas(_returnVal1DatosFacturaEmitidaFacturasAgrupadas);
            respuestaconsultalr.FacturaRespuestaType.FacturasRectificadas _returnVal1DatosFacturaEmitidaFacturasRectificadas = new respuestaconsultalr.FacturaRespuestaType.FacturasRectificadas();
            java.util.List<suministroinformacion.IDFacturaARType> _returnVal1DatosFacturaEmitidaFacturasRectificadasIDFacturaRectificada = new java.util.ArrayList<suministroinformacion.IDFacturaARType>();
            _returnVal1DatosFacturaEmitidaFacturasRectificadas.getIDFacturaRectificada().addAll(_returnVal1DatosFacturaEmitidaFacturasRectificadasIDFacturaRectificada);
            _returnVal1DatosFacturaEmitida.setFacturasRectificadas(_returnVal1DatosFacturaEmitidaFacturasRectificadas);
            suministroinformacion.DesgloseRectificacionType _returnVal1DatosFacturaEmitidaImporteRectificacion = new suministroinformacion.DesgloseRectificacionType();
            _returnVal1DatosFacturaEmitidaImporteRectificacion.setBaseRectificada("BaseRectificada899578382");
            _returnVal1DatosFacturaEmitidaImporteRectificacion.setCuotaRectificada("CuotaRectificada-58231150");
            _returnVal1DatosFacturaEmitidaImporteRectificacion.setCuotaRecargoRectificado("CuotaRecargoRectificado-17520137");
            _returnVal1DatosFacturaEmitida.setImporteRectificacion(_returnVal1DatosFacturaEmitidaImporteRectificacion);
            _returnVal1DatosFacturaEmitida.setFechaOperacion("FechaOperacion-605679990");
            _returnVal1DatosFacturaEmitida.setClaveRegimenEspecialOTrascendencia("ClaveRegimenEspecialOTrascendencia1503713518");
            _returnVal1DatosFacturaEmitida.setClaveRegimenEspecialOTrascendenciaAdicional1("ClaveRegimenEspecialOTrascendenciaAdicional1747991205");
            _returnVal1DatosFacturaEmitida.setClaveRegimenEspecialOTrascendenciaAdicional2("ClaveRegimenEspecialOTrascendenciaAdicional294530118");
            _returnVal1DatosFacturaEmitida.setNumRegistroAcuerdoFacturacion("NumRegistroAcuerdoFacturacion1274275515");
            _returnVal1DatosFacturaEmitida.setImporteTotal("ImporteTotal731570029");
            _returnVal1DatosFacturaEmitida.setBaseImponibleACoste("BaseImponibleACoste476044922");
            _returnVal1DatosFacturaEmitida.setDescripcionOperacion("DescripcionOperacion1348765782");
            respuestaconsultalr.FacturaRespuestaExpedidaType.DatosInmueble _returnVal1DatosFacturaEmitidaDatosInmueble = new respuestaconsultalr.FacturaRespuestaExpedidaType.DatosInmueble();
            java.util.List<suministroinformacion.DatosInmuebleType> _returnVal1DatosFacturaEmitidaDatosInmuebleDetalleInmueble = new java.util.ArrayList<suministroinformacion.DatosInmuebleType>();
            _returnVal1DatosFacturaEmitidaDatosInmueble.getDetalleInmueble().addAll(_returnVal1DatosFacturaEmitidaDatosInmuebleDetalleInmueble);
            _returnVal1DatosFacturaEmitida.setDatosInmueble(_returnVal1DatosFacturaEmitidaDatosInmueble);
            _returnVal1DatosFacturaEmitida.setImporteTransmisionSujetoAIVA("ImporteTransmisionSujetoAIVA1475105422");
            suministroinformacion.EmitidaPorTercerosType _returnVal1DatosFacturaEmitidaEmitidaPorTerceros = suministroinformacion.EmitidaPorTercerosType.S;
            _returnVal1DatosFacturaEmitida.setEmitidaPorTerceros(_returnVal1DatosFacturaEmitidaEmitidaPorTerceros);
            suministroinformacion.VariosDestinatariosType _returnVal1DatosFacturaEmitidaVariosDestinatarios = suministroinformacion.VariosDestinatariosType.N;
            _returnVal1DatosFacturaEmitida.setVariosDestinatarios(_returnVal1DatosFacturaEmitidaVariosDestinatarios);
            suministroinformacion.CuponType _returnVal1DatosFacturaEmitidaCupon = suministroinformacion.CuponType.N;
            _returnVal1DatosFacturaEmitida.setCupon(_returnVal1DatosFacturaEmitidaCupon);
            suministroinformacion.PersonaFisicaJuridicaType _returnVal1DatosFacturaEmitidaContraparte = new suministroinformacion.PersonaFisicaJuridicaType();
            _returnVal1DatosFacturaEmitidaContraparte.setNombreRazon("NombreRazon-735571428");
            _returnVal1DatosFacturaEmitidaContraparte.setNIFRepresentante("NIFRepresentante1066171595");
            _returnVal1DatosFacturaEmitidaContraparte.setNIF("NIF-870362508");
            suministroinformacion.IDOtroType _returnVal1DatosFacturaEmitidaContraparteIDOtro = new suministroinformacion.IDOtroType();
            suministroinformacion.CountryType2 _returnVal1DatosFacturaEmitidaContraparteIDOtroCodigoPais = suministroinformacion.CountryType2.AQ;
            _returnVal1DatosFacturaEmitidaContraparteIDOtro.setCodigoPais(_returnVal1DatosFacturaEmitidaContraparteIDOtroCodigoPais);
            _returnVal1DatosFacturaEmitidaContraparteIDOtro.setIDType("IDType1670060441");
            _returnVal1DatosFacturaEmitidaContraparteIDOtro.setID("ID-1205138829");
            _returnVal1DatosFacturaEmitidaContraparte.setIDOtro(_returnVal1DatosFacturaEmitidaContraparteIDOtro);
            _returnVal1DatosFacturaEmitida.setContraparte(_returnVal1DatosFacturaEmitidaContraparte);
            respuestaconsultalr.FacturaRespuestaExpedidaType.TipoDesglose _returnVal1DatosFacturaEmitidaTipoDesglose = new respuestaconsultalr.FacturaRespuestaExpedidaType.TipoDesglose();
            suministroinformacion.TipoSinDesgloseType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFactura = new suministroinformacion.TipoSinDesgloseType();
            suministroinformacion.SujetaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujeta = new suministroinformacion.SujetaType();
            suministroinformacion.SujetaType.Exenta _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaExenta = new suministroinformacion.SujetaType.Exenta();
            suministroinformacion.CausaExencionType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaExentaCausaExencion = suministroinformacion.CausaExencionType.E_5;
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaExenta.setCausaExencion(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaExentaCausaExencion);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaExenta.setBaseImponible("BaseImponible2001394405");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujeta.setExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaExenta);
            suministroinformacion.SujetaType.NoExenta _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExenta = new suministroinformacion.SujetaType.NoExenta();
            suministroinformacion.TipoOperacionSujetaNoExentaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExentaTipoNoExenta = suministroinformacion.TipoOperacionSujetaNoExentaType.S_3;
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExenta.setTipoNoExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExentaTipoNoExenta);
            suministroinformacion.SujetaType.NoExenta.DesgloseIVA _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVA = new suministroinformacion.SujetaType.NoExenta.DesgloseIVA();
            java.util.List<suministroinformacion.DetalleIVAEmitidaType> _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVADetalleIVA = new java.util.ArrayList<suministroinformacion.DetalleIVAEmitidaType>();
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVA.getDetalleIVA().addAll(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVADetalleIVA);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExenta.setDesgloseIVA(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExentaDesgloseIVA);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujeta.setNoExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujetaNoExenta);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFactura.setSujeta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaSujeta);
            suministroinformacion.NoSujetaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaNoSujeta = new suministroinformacion.NoSujetaType();
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaNoSujeta.setImportePorArticulos714Otros("ImportePorArticulos714Otros1552653784");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaNoSujeta.setImporteTAIReglasLocalizacion("ImporteTAIReglasLocalizacion456902972");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFactura.setNoSujeta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFacturaNoSujeta);
            _returnVal1DatosFacturaEmitidaTipoDesglose.setDesgloseFactura(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseFactura);
            suministroinformacion.TipoConDesgloseType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacion = new suministroinformacion.TipoConDesgloseType();
            suministroinformacion.TipoSinDesglosePrestacionType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios = new suministroinformacion.TipoSinDesglosePrestacionType();
            suministroinformacion.SujetaPrestacionType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta = new suministroinformacion.SujetaPrestacionType();
            suministroinformacion.SujetaPrestacionType.Exenta _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta = new suministroinformacion.SujetaPrestacionType.Exenta();
            suministroinformacion.CausaExencionType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExentaCausaExencion = suministroinformacion.CausaExencionType.E_6;
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta.setCausaExencion(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExentaCausaExencion);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta.setBaseImponible("BaseImponible-849084492");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta.setExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaExenta);
            suministroinformacion.SujetaPrestacionType.NoExenta _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta = new suministroinformacion.SujetaPrestacionType.NoExenta();
            suministroinformacion.TipoOperacionSujetaNoExentaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaTipoNoExenta = suministroinformacion.TipoOperacionSujetaNoExentaType.S_2;
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta.setTipoNoExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaTipoNoExenta);
            suministroinformacion.SujetaPrestacionType.NoExenta.DesgloseIVA _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVA = new suministroinformacion.SujetaPrestacionType.NoExenta.DesgloseIVA();
            java.util.List<suministroinformacion.DetalleIVAEmitidaPrestacionType> _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVADetalleIVA = new java.util.ArrayList<suministroinformacion.DetalleIVAEmitidaPrestacionType>();
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVA.getDetalleIVA().addAll(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVADetalleIVA);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta.setDesgloseIVA(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExentaDesgloseIVA);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta.setNoExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujetaNoExenta);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios.setSujeta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosSujeta);
            suministroinformacion.NoSujetaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta = new suministroinformacion.NoSujetaType();
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta.setImportePorArticulos714Otros("ImportePorArticulos714Otros676947850");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta.setImporteTAIReglasLocalizacion("ImporteTAIReglasLocalizacion1854616012");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios.setNoSujeta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServiciosNoSujeta);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacion.setPrestacionServicios(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionPrestacionServicios);
            suministroinformacion.TipoSinDesgloseType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntrega = new suministroinformacion.TipoSinDesgloseType();
            suministroinformacion.SujetaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta = new suministroinformacion.SujetaType();
            suministroinformacion.SujetaType.Exenta _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta = new suministroinformacion.SujetaType.Exenta();
            suministroinformacion.CausaExencionType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExentaCausaExencion = suministroinformacion.CausaExencionType.E_3;
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta.setCausaExencion(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExentaCausaExencion);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta.setBaseImponible("BaseImponible1007749160");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta.setExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaExenta);
            suministroinformacion.SujetaType.NoExenta _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta = new suministroinformacion.SujetaType.NoExenta();
            suministroinformacion.TipoOperacionSujetaNoExentaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaTipoNoExenta = suministroinformacion.TipoOperacionSujetaNoExentaType.S_3;
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta.setTipoNoExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaTipoNoExenta);
            suministroinformacion.SujetaType.NoExenta.DesgloseIVA _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVA = new suministroinformacion.SujetaType.NoExenta.DesgloseIVA();
            java.util.List<suministroinformacion.DetalleIVAEmitidaType> _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVADetalleIVA = new java.util.ArrayList<suministroinformacion.DetalleIVAEmitidaType>();
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVA.getDetalleIVA().addAll(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVADetalleIVA);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta.setDesgloseIVA(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExentaDesgloseIVA);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta.setNoExenta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujetaNoExenta);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntrega.setSujeta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaSujeta);
            suministroinformacion.NoSujetaType _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta = new suministroinformacion.NoSujetaType();
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta.setImportePorArticulos714Otros("ImportePorArticulos714Otros-432242679");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta.setImporteTAIReglasLocalizacion("ImporteTAIReglasLocalizacion1116299031");
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntrega.setNoSujeta(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntregaNoSujeta);
            _returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacion.setEntrega(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacionEntrega);
            _returnVal1DatosFacturaEmitidaTipoDesglose.setDesgloseTipoOperacion(_returnVal1DatosFacturaEmitidaTipoDesgloseDesgloseTipoOperacion);
            _returnVal1DatosFacturaEmitida.setTipoDesglose(_returnVal1DatosFacturaEmitidaTipoDesglose);
            respuestaconsultalr.FacturaARType _returnVal1DatosFacturaEmitidaCobros = respuestaconsultalr.FacturaARType.S;
            _returnVal1DatosFacturaEmitida.setCobros(_returnVal1DatosFacturaEmitidaCobros);
            _returnVal1.setDatosFacturaEmitida(_returnVal1DatosFacturaEmitida);
            suministroinformacion.DatosPresentacion2Type _returnVal1DatosPresentacion = new suministroinformacion.DatosPresentacion2Type();
            _returnVal1DatosPresentacion.setNIFPresentador("NIFPresentador-257950721");
            _returnVal1DatosPresentacion.setTimestampPresentacion("TimestampPresentacion239081158");
            _returnVal1DatosPresentacion.setCSV("CSV136312515");
            _returnVal1.setDatosPresentacion(_returnVal1DatosPresentacion);
            respuestaconsultalr.EstadoFacturaType _returnVal1EstadoFactura = new respuestaconsultalr.EstadoFacturaType();
            _returnVal1EstadoFactura.setEstadoCuadre("EstadoCuadre1471009715");
            _returnVal1EstadoFactura.setTimestampEstadoCuadre("TimestampEstadoCuadre-1324384490");
            _returnVal1EstadoFactura.setTimestampUltimaModificacion("TimestampUltimaModificacion-1757840049");
            respuestaconsultalr.EstadoRegistroSIIType _returnVal1EstadoFacturaEstadoRegistro = respuestaconsultalr.EstadoRegistroSIIType.ACEPTADA_CON_ERRORES;
            _returnVal1EstadoFactura.setEstadoRegistro(_returnVal1EstadoFacturaEstadoRegistro);
            _returnVal1EstadoFactura.setCodigoErrorRegistro(new java.math.BigInteger("89205571517108703504597567233071990411"));
            _returnVal1EstadoFactura.setDescripcionErrorRegistro("DescripcionErrorRegistro196465493");
            _returnVal1.setEstadoFactura(_returnVal1EstadoFactura);
            respuestaconsultalr.DatosDescuadreContraparteType _returnVal1DatosDescuadreContraparte = new respuestaconsultalr.DatosDescuadreContraparteType();
            _returnVal1DatosDescuadreContraparte.setSumBaseImponibleISP("SumBaseImponibleISP-2140902394");
            _returnVal1DatosDescuadreContraparte.setSumBaseImponible("SumBaseImponible71770365");
            _returnVal1DatosDescuadreContraparte.setSumCuota("SumCuota-9770839");
            _returnVal1DatosDescuadreContraparte.setSumCuotaRecargoEquivalencia("SumCuotaRecargoEquivalencia1558661154");
            _returnVal1DatosDescuadreContraparte.setImporteTotal("ImporteTotal588700649");
            _returnVal1.setDatosDescuadreContraparte(_returnVal1DatosDescuadreContraparte);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see siisoap.suministrofactemitidas.SiiSOAP#anulacionLRFacturasEmitidas(https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.ssii.fact.ws.suministrolr.BajaLRFacturasEmitidas anulacionLRFacturasEmitidas)*
     */
    public respuestasuministro.RespuestaLRBajaFEmitidasType anulacionLRFacturasEmitidas(suministrolr.BajaLRFacturasEmitidas anulacionLRFacturasEmitidas) { 
        LOG.info("Executing operation anulacionLRFacturasEmitidas");
        System.out.println(anulacionLRFacturasEmitidas);
        try {
            respuestasuministro.RespuestaLRBajaFEmitidasType _return = new respuestasuministro.RespuestaLRBajaFEmitidasType();
            _return.setCSV("CSV-890289261");
            suministroinformacion.DatosPresentacionType _returnDatosPresentacion = new suministroinformacion.DatosPresentacionType();
            _returnDatosPresentacion.setNIFPresentador("NIFPresentador-1334322533");
            _returnDatosPresentacion.setTimestampPresentacion("TimestampPresentacion-2137092785");
            _return.setDatosPresentacion(_returnDatosPresentacion);
            suministroinformacion.CabeceraSiiBaja _returnCabecera = new suministroinformacion.CabeceraSiiBaja();
            _returnCabecera.setIDVersionSii("IDVersionSii-109706108");
            suministroinformacion.PersonaFisicaJuridicaESType _returnCabeceraTitular = new suministroinformacion.PersonaFisicaJuridicaESType();
            _returnCabeceraTitular.setNombreRazon("NombreRazon-882639713");
            _returnCabeceraTitular.setNIFRepresentante("NIFRepresentante-1474874159");
            _returnCabeceraTitular.setNIF("NIF2112502930");
            _returnCabecera.setTitular(_returnCabeceraTitular);
            _return.setCabecera(_returnCabecera);
            respuestasuministro.EstadoEnvioType _returnEstadoEnvio = respuestasuministro.EstadoEnvioType.PARCIALMENTE_CORRECTO;
            _return.setEstadoEnvio(_returnEstadoEnvio);
            java.util.List<respuestasuministro.RespuestaExpedidaBajaType> _returnRespuestaLinea = new java.util.ArrayList<respuestasuministro.RespuestaExpedidaBajaType>();
            respuestasuministro.RespuestaExpedidaBajaType _returnRespuestaLineaVal1 = new respuestasuministro.RespuestaExpedidaBajaType();
            suministroinformacion.IDFacturaExpedidaType _returnRespuestaLineaVal1IDFactura = new suministroinformacion.IDFacturaExpedidaType();
            suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura _returnRespuestaLineaVal1IDFacturaIDEmisorFactura = new suministroinformacion.IDFacturaExpedidaType.IDEmisorFactura();
            _returnRespuestaLineaVal1IDFacturaIDEmisorFactura.setNIF("NIF-1548687967");
            _returnRespuestaLineaVal1IDFactura.setIDEmisorFactura(_returnRespuestaLineaVal1IDFacturaIDEmisorFactura);
            _returnRespuestaLineaVal1IDFactura.setNumSerieFacturaEmisor("NumSerieFacturaEmisor-814982765");
            _returnRespuestaLineaVal1IDFactura.setNumSerieFacturaEmisorResumenFin("NumSerieFacturaEmisorResumenFin655672260");
            _returnRespuestaLineaVal1IDFactura.setFechaExpedicionFacturaEmisor("FechaExpedicionFacturaEmisor961341105");
            _returnRespuestaLineaVal1.setIDFactura(_returnRespuestaLineaVal1IDFactura);
            respuestasuministro.EstadoRegistroType _returnRespuestaLineaVal1EstadoRegistro = respuestasuministro.EstadoRegistroType.CORRECTO;
            _returnRespuestaLineaVal1.setEstadoRegistro(_returnRespuestaLineaVal1EstadoRegistro);
            _returnRespuestaLineaVal1.setCodigoErrorRegistro(new java.math.BigInteger("15907417605578979962944690639353265355"));
            _returnRespuestaLineaVal1.setDescripcionErrorRegistro("DescripcionErrorRegistro144253320");
            _returnRespuestaLineaVal1.setCSV("CSV1359646013");
            _returnRespuestaLinea.add(_returnRespuestaLineaVal1);
            _return.getRespuestaLinea().addAll(_returnRespuestaLinea);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
